import { User, Project, Sprint, Issue, Activity } from '../types';

export const mockUsers: User[] = [
  {
    id: 'u1',
    name: 'Harshit Kanjariya',
    email: 'kanjariyaharshit@gmail.com',
    avatarUrl: 'https://i.pravatar.cc/150?u=u1',
    role: 'ADMIN',
    jobTitle: 'Senior Software Engineer',
    department: 'Engineering',
    location: 'San Francisco, CA',
    bio: 'Passionate about building great software and collaborating with amazing teams.',
    timezone: 'America/Los_Angeles',
  },
  {
    id: 'u2',
    name: 'John Doe',
    email: 'john@example.com',
    avatarUrl: 'https://i.pravatar.cc/150?u=u2',
    role: 'MEMBER',
    jobTitle: 'Product Manager',
    department: 'Product',
    location: 'New York, NY',
    timezone: 'America/New_York',
  },
  {
    id: 'u3',
    name: 'Sara Smith',
    email: 'sara@example.com',
    avatarUrl: 'https://i.pravatar.cc/150?u=u3',
    role: 'MEMBER',
    jobTitle: 'UX Designer',
    department: 'Design',
    location: 'London, UK',
    timezone: 'Europe/London',
  },
  {
    id: 'u4',
    name: 'Alex Johnson',
    email: 'alex@example.com',
    avatarUrl: 'https://i.pravatar.cc/150?u=u4',
    role: 'MEMBER',
    jobTitle: 'Frontend Developer',
    department: 'Engineering',
  },
];

export const mockProjects: Project[] = [
  {
    id: 'p1',
    key: 'CLOUD',
    name: 'Cloud Infrastructure',
    description: 'Managing our global cloud resources and scaling strategies.',
    type: 'SCRUM',
    leadId: 'u1',
    color: '#0052CC',
    memberIds: ['u1', 'u2', 'u3', 'u4'],
    updatedAt: new Date().toISOString(),
    isStarred: true,
  },
  {
    id: 'p2',
    key: 'MAPP',
    name: 'Mobile Application',
    description: 'Next-gen mobile app for iOS and Android platforms.',
    type: 'KANBAN',
    leadId: 'u2',
    color: '#00875A',
    memberIds: ['u1', 'u2'],
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p3',
    key: 'DASH',
    name: 'Analytics Dashboard',
    description: 'Internal dashboard for real-time data visualization.',
    type: 'SCRUM',
    leadId: 'u3',
    color: '#6554C0',
    memberIds: ['u1', 'u3'],
    updatedAt: new Date().toISOString(),
  },
];

export const mockSprints: Sprint[] = [
  {
    id: 's1',
    projectId: 'p1',
    name: 'Sprint 1',
    startDate: '2026-03-01T00:00:00Z',
    endDate: '2026-03-14T00:00:00Z',
    goal: 'Complete core infrastructure setup.',
    status: 'COMPLETED',
  },
  {
    id: 's2',
    projectId: 'p1',
    name: 'Sprint 2',
    startDate: '2026-03-15T00:00:00Z',
    endDate: '2026-03-31T00:00:00Z',
    goal: 'Implement monitoring and logging.',
    status: 'ACTIVE',
  },
];

export const mockIssues: Issue[] = [
  {
    id: 'i1',
    key: 'CLOUD-1',
    projectId: 'p1',
    sprintId: 's2',
    type: 'STORY',
    summary: 'Setup AWS Lambda functions for data processing',
    description: 'We need to implement serverless functions to handle incoming data streams from the IoT sensors.',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assigneeId: 'u1',
    reporterId: 'u2',
    storyPoints: 5,
    labels: ['backend', 'aws'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isStarred: true,
  },
  {
    id: 'i2',
    key: 'CLOUD-2',
    projectId: 'p1',
    sprintId: 's2',
    type: 'BUG',
    summary: 'Fix memory leak in the data ingestion service',
    description: 'The ingestion service is consuming increasing amounts of memory over time, leading to crashes.',
    status: 'TODO',
    priority: 'HIGHEST',
    assigneeId: 'u2',
    reporterId: 'u1',
    storyPoints: 8,
    labels: ['bug', 'performance'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'i3',
    key: 'MAPP-1',
    projectId: 'p2',
    type: 'TASK',
    summary: 'Design new login screen UI',
    description: 'Create a modern, user-friendly login screen following the new brand guidelines.',
    status: 'IN_REVIEW',
    priority: 'MEDIUM',
    assigneeId: 'u3',
    reporterId: 'u2',
    storyPoints: 3,
    labels: ['ui', 'design'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'i4',
    key: 'DASH-1',
    projectId: 'p3',
    type: 'EPIC',
    summary: 'Real-time Charting Engine',
    description: 'Core engine to handle high-frequency data updates for the dashboard charts.',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assigneeId: 'u1',
    reporterId: 'u3',
    labels: ['core', 'analytics'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockActivities: Activity[] = [
  {
    id: 'a1',
    userId: 'u1',
    issueId: 'i1',
    action: 'moved',
    target: 'CLOUD-1 to In Progress',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: 'a2',
    userId: 'u2',
    issueId: 'i3',
    action: 'commented on',
    target: 'MAPP-1',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: 'a3',
    userId: 'u1',
    projectId: 'p3',
    action: 'created',
    target: 'DASH-1 Epic',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];
